version: 2
updates:
- package-ecosystem: mix
  directory: "backend-elixir/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "frontend-sveltekit/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  
